/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/HNUFfPxvIGU
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export default function mymenu() {
  return (
    <div className="flex flex-col h-screen">
      <header className="bg-primary text-primary-foreground py-4 px-6">
        <div className="max-w-6xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-2">
            <BarChartIcon className="h-6 w-6" />
            <h1 className="text-2xl font-bold">Portfolio Visualizer</h1>
          </div>
          <div />
        </div>
      </header>
      <main className="flex-1 bg-background text-foreground">
        <div className="max-w-6xl mx-auto py-8 px-6">
          <section className="mb-8">
            <h2 className="text-xl font-bold mb-4">Upload Portfolio</h2>
            <div className="bg-card p-6 rounded-lg shadow">
              <div />
            </div>
          </section>
          <section className="mb-8">
            <h2 className="text-xl font-bold mb-4">Portfolio Performance</h2>
            <div className="bg-card p-6 rounded-lg shadow">
              <div />
            </div>
          </section>
          <section className="mb-8">
            <h2 className="text-xl font-bold mb-4">Compare to Benchmark</h2>
            <div className="bg-card p-6 rounded-lg shadow">
              <div />
            </div>
          </section>
          <section>
            <h2 className="text-xl font-bold mb-4">Portfolio Dashboard</h2>
            <div className="bg-card p-6 rounded-lg shadow">
              <div />
            </div>
          </section>
        </div>
      </main>
    </div>
  )
}

function BarChartIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="12" x2="12" y1="20" y2="10" />
      <line x1="18" x2="18" y1="20" y2="4" />
      <line x1="6" x2="6" y1="20" y2="16" />
    </svg>
  )
}
