/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/tPXZy4OcuZq
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function perf() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="bg-primary text-primary-foreground py-4 px-6 shadow">
        <div className="container mx-auto flex items-center justify-between">
          <Link href="#" className="text-xl font-bold" prefetch={false}>
            Stock Portfolio Tracker
          </Link>
          <div />
        </div>
      </header>
      <main className="flex-1 py-8 px-4 md:px-8">
        <div className="container mx-auto">
          <section className="mb-8">
            <h2 className="text-2xl font-bold mb-4">Upload Portfolio</h2>
            <div className="bg-background rounded-lg shadow p-6">
              <div />
            </div>
          </section>
          <section>
            <h2 className="text-2xl font-bold mb-4">Portfolio Performance</h2>
            <div className="bg-background rounded-lg shadow p-6">
              <div />
              <div />
              <div />
            </div>
          </section>
        </div>
      </main>
      <footer className="bg-muted text-muted-foreground py-4 px-6 mt-auto">
        <div className="container mx-auto text-center text-sm">
          &copy; 2024 Stock Portfolio Tracker. All rights reserved.
        </div>
      </footer>
    </div>
  )
}
