/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/S2qnlUE1C9t
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem } from "@/components/ui/dropdown-menu"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { ChartContainer, ChartTooltip, ChartTooltipContent } from "@/components/ui/chart"
import { LineChart, CartesianGrid, XAxis, Line } from "recharts"

export function upload() {
  return (
    <div className="flex min-h-screen flex-col bg-background">
      <header className="sticky top-0 z-40 border-b bg-background">
        <div className="container mx-auto flex h-16 items-center justify-between px-4 sm:px-6 lg:px-8">
          <Link href="#" className="flex items-center gap-2 font-bold" prefetch={false}>
            <BarChartIcon className="h-6 w-6" />
            Portfolio Tracker
          </Link>
          <div className="flex items-center gap-4">
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="ghost" size="icon">
                  <img
                    src="/placeholder.svg"
                    alt="User avatar"
                    width={32}
                    height={32}
                    className="rounded-full"
                    style={{ aspectRatio: "32/32", objectFit: "cover" }}
                  />
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end">
                <DropdownMenuLabel>Signed in as</DropdownMenuLabel>
                <DropdownMenuSeparator />
                <DropdownMenuItem>
                  <div className="flex items-center gap-2">
                    <img
                      src="/placeholder.svg"
                      alt="User avatar"
                      width={24}
                      height={24}
                      className="rounded-full"
                      style={{ aspectRatio: "24/24", objectFit: "cover" }}
                    />
                    <div className="grid gap-0.5">
                      <p className="text-sm font-medium">John Doe</p>
                      <p className="text-xs text-muted-foreground">john@example.com</p>
                    </div>
                  </div>
                </DropdownMenuItem>
                <DropdownMenuSeparator />
                <DropdownMenuItem>Sign out</DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        </div>
      </header>
      <main className="flex-1 px-4 py-8 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-4xl">
          <div className="grid gap-8">
            <Card>
              <CardHeader>
                <CardTitle>Upload Portfolio</CardTitle>
                <CardDescription>Upload a CSV file with your stock portfolio data.</CardDescription>
              </CardHeader>
              <CardContent>
                <form>
                  <div className="grid gap-4">
                    <div className="grid gap-2">
                      <Label htmlFor="file">CSV File</Label>
                      <Input type="file" id="file" accept=".csv" placeholder="Choose file" />
                    </div>
                    <Button type="submit">Upload</Button>
                  </div>
                </form>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Portfolio Performance</CardTitle>
                <CardDescription>
                  View your portfolio's net asset value (NAV) against a benchmark index.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <ChartContainer
                  config={{
                    portfolio: { label: "Portfolio", color: "hsl(var(--chart-1))" },
                    benchmark: { label: "Benchmark", color: "hsl(var(--chart-2))" },
                  }}
                  className="min-h-[400px]"
                >
                  <LineChart
                    accessibilityLayer
                    data={[
                      { date: "Jan 1", portfolio: 100000, benchmark: 100000 },
                      { date: "Feb 1", portfolio: 105000, benchmark: 102000 },
                      { date: "Mar 1", portfolio: 108000, benchmark: 103500 },
                      { date: "Apr 1", portfolio: 112000, benchmark: 105000 },
                      { date: "May 1", portfolio: 115000, benchmark: 106500 },
                      { date: "Jun 1", portfolio: 118000, benchmark: 108000 },
                    ]}
                    margin={{ left: 12, right: 12 }}
                  >
                    <CartesianGrid vertical={false} />
                    <XAxis dataKey="date" tickLine={false} axisLine={false} tickMargin={8} />
                    <ChartTooltip cursor={false} content={<ChartTooltipContent indicator="dashed" />} />
                    <Line
                      dataKey="portfolio"
                      type="natural"
                      stroke="var(--color-portfolio)"
                      strokeWidth={2}
                      dot={false}
                    />
                    <Line
                      dataKey="benchmark"
                      type="natural"
                      stroke="var(--color-benchmark)"
                      strokeWidth={2}
                      dot={false}
                    />
                  </LineChart>
                </ChartContainer>
              </CardContent>
            </Card>
          </div>
        </div>
      </main>
      <footer className="border-t bg-background">
        <div className="container mx-auto flex h-16 items-center justify-between px-4 sm:px-6 lg:px-8">
          <p className="text-sm text-muted-foreground">&copy; 2024 Portfolio Tracker. All rights reserved.</p>
          <div className="flex items-center gap-4">
            <Link href="#" className="text-sm text-muted-foreground hover:text-foreground" prefetch={false}>
              Privacy Policy
            </Link>
            <Link href="#" className="text-sm text-muted-foreground hover:text-foreground" prefetch={false}>
              Terms of Service
            </Link>
          </div>
        </div>
      </footer>
    </div>
  )
}

function BarChartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="12" x2="12" y1="20" y2="10" />
      <line x1="18" x2="18" y1="20" y2="4" />
      <line x1="6" x2="6" y1="20" y2="16" />
    </svg>
  )
}
